// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbpqMhnOhjd1PNALo0IHDp-ktjoPB23UQ',
    appId: '1:446427782153:web:1196526e4ad252147becd8',
    messagingSenderId: '446427782153',
    projectId: 'my-fcm-89018',
    authDomain: 'my-fcm-89018.firebaseapp.com',
    storageBucket: 'my-fcm-89018.firebasestorage.app',
    measurementId: 'G-YD5SEDZBQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-alCc1fRD65gVrIpJL03ndwmQkJ0dc70',
    appId: '1:446427782153:android:4dab1e30abe6b31b7becd8',
    messagingSenderId: '446427782153',
    projectId: 'my-fcm-89018',
    storageBucket: 'my-fcm-89018.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEg5CkZlQyTQ3_kbmqMMFdL659bA7_ev0',
    appId: '1:446427782153:ios:23f92901992052367becd8',
    messagingSenderId: '446427782153',
    projectId: 'my-fcm-89018',
    storageBucket: 'my-fcm-89018.firebasestorage.app',
    iosBundleId: 'com.example.cleanUpCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEg5CkZlQyTQ3_kbmqMMFdL659bA7_ev0',
    appId: '1:446427782153:ios:23f92901992052367becd8',
    messagingSenderId: '446427782153',
    projectId: 'my-fcm-89018',
    storageBucket: 'my-fcm-89018.firebasestorage.app',
    iosBundleId: 'com.example.cleanUpCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbpqMhnOhjd1PNALo0IHDp-ktjoPB23UQ',
    appId: '1:446427782153:web:f0fda12bd275a14d7becd8',
    messagingSenderId: '446427782153',
    projectId: 'my-fcm-89018',
    authDomain: 'my-fcm-89018.firebaseapp.com',
    storageBucket: 'my-fcm-89018.firebasestorage.app',
    measurementId: 'G-HWEPVKSTYN',
  );
}
